//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCube.Models {
   using System;
   using System.Collections.Generic;

   public partial class Programmers_Skills {
      public int ProgrammerID { get; set; }
      public Nullable<int> SkillID { get; set; }

      public virtual Programmer Programmer { get; set; }
      public virtual Skill Skill { get; set; }
   }
}
